### PR TITLE
4AM gibberish

### LINKED ISSUE #267: IPs are broken with websocket connections
https://github.com/Akuli/catris/blob/3fc3eabf06dab236340e4fe7057a11bf1f526e9d/src/main.rs#L246-L250

This is pretty broken. Currently websocket connections only listen to localhost, so this IP is always 127.0.0.1. It causes useless logging and actually makes catris unusable if more than 5 people try to play simultaneously with the web UI.

### LINKED ISSUE #268: local-playing is broken
https://github.com/Akuli/catris/blob/63fa74d43b50cb94a32fbc8378650b56c88bd71a/src/main.rs#L227

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #268 
Fixes #267

### CODE REVIEW

File: src/connection.rs [hunk 1]
```diff
@@ -191,10 +201,143 @@ impl Sender {
     }
 }
 
+pub struct IpTracker {
```
Comment (Akuli) [inline src/connection.rs:204]: All this stuff should go into new file

File: README.md [hunk 2]
```diff
@@ -28,6 +28,16 @@ This means that the javascript code in `web-ui/` must interpret ANSI codes,
 but this also makes the rust code simpler:
 it needs to use ANSI codes for raw TCP connections anyway.
 
+The purpose of `ip_tracker.rs` is to limit the number of simultaneous connections for each IP address
+and to log the IP if someone is creating many connections.
```
Comment (Akuli) [inline README.md:32]:
```suggestion
and to log IPs that spam the server with many connections.
```

File: README.md [hunk 3]
```diff
@@ -28,6 +28,16 @@ This means that the javascript code in `web-ui/` must interpret ANSI codes,
...
+This way IP addresses of most users are only stored in RAM (as they would be anyways),
```
Comment (Akuli) [inline README.md:33]:
```suggestion
This way most IP addresses are stored only in RAM (which is needed anyway),
```

File: README.md [hunk 4]
```diff
@@ -28,6 +28,16 @@ This means that the javascript code in `web-ui/` must interpret ANSI codes,
...
+and not written to disk, as many users don't want me to know their IP address.
+The IP address passed to `ip_tracker.rs` is determined in `connection.rs`:
+it uses a header named `X-Real-IP` (set in the nginx configuration) when proxied through nginx,
+and otherwise the IP that the connection to the rust program came from.
+To keep track of how many clients are currently connected from each IP,
+`ip_tracker.rs` also returns a token object that should be dropped when a client disconnects.
```
Comment (Akuli) [inline README.md:39]:
```suggestion
`ip_tracker.rs` also returns a token object that is dropped when a client disconnects.
```

File: catris.service [hunk 5]
```diff
@@ -16,6 +16,7 @@ Description=catris
 [Service]
 ExecStart=/home/catris/catris
 Environment="RUST_BACKTRACE=1"
+Environment="CATRIS_WEBSOCKET_PROXIED=1"
```
Comment (Akuli) [inline catris.service:19]: This could be an IP address, in case proxy and rust program are on different servers.

File: src/connection.rs [hunk 6]
```diff
@@ -191,10 +210,83 @@ impl Sender {
     }
 }
 
+/*
+tokio-tungstenite offers a callback trait that gets called when connecting.
+Two WTF's here: 1) why is async library using callbacks? 2) why is it a trait and not FnMut?
+It is the only way to access the headers from nginx...
+
+To test that this gets a correct ip, create a file req.txt with this in it and TWO BLANK LINES after:
```
Comment (Akuli) [inline src/connection.rs:218]:
```suggestion
To test that this gets the ip, create a file req.txt with this in it and TWO BLANK LINES after.
This file represents what nginx would sends when proxying.
```

File: src/connection.rs [hunk 7]
```diff
@@ -191,10 +210,83 @@ impl Sender {
...
+struct CheckRealIpCallback {
+    logger: ClientLogger,
+    ip_tracker: Arc<Mutex<IpTracker>>,
+    decrementers: Vec<ForgetClientOnDrop>,
+}
+impl Callback for &mut CheckRealIpCallback {
+    fn on_request(self, request: &Request, response: Response) -> Result<Response, ErrorResponse> {
+        let ip: IpAddr = request
+            .headers()
+            .get("x-real-ip")
```
Comment (Akuli) [inline src/connection.rs:252]: more greppable
```suggestion
            .get("X-Real-IP")
```

File: src/connection.rs [hunk 8]
```diff
@@ -211,6 +303,17 @@ pub async fn initialize_connection(
     let sender;
     let receiver;
 
+    let mut decrementer: Option<ForgetClientOnDrop>;
+    if is_websocket && websocket_connections_come_from_a_proxy() {
+        // Websocket connections should go through nginx and arrive to this process from localhost.
+        // In fact it only listens on localhost (aka loopback).
+        assert!(source_ip.is_loopback());
```
Comment (Akuli) [inline src/connection.rs:310]: This will need updating if the environment variable becomes an IP address

File: src/connection.rs [hunk 9]
```diff
@@ -220,10 +323,30 @@ pub async fn initialize_connection(
             max_frame_size: Some(1024),
             ..Default::default()
         };
-        let ws = tokio_tungstenite::accept_async_with_config(socket, Some(config))
-            .await
-            .map_err(convert_error)?;
-        let (ws_writer, ws_reader) = ws.split();
+
+        let ws_result;
```
Comment (Akuli) [inline src/connection.rs:327]: Should probably be named just `ws`

File: src/ip_tracker.rs [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+    ip_tracker: Arc<Mutex<IpTracker>>,
+}
+impl Drop for ForgetClientOnDrop {
+    fn drop(&mut self) {
+        let mut tracker = self.ip_tracker.lock().unwrap();
+        let n = *tracker.client_counts_by_ip.get(&self.ip).unwrap();
+        assert!(n > 0);
+        if n == 1 {
+            // last client
+            _ = tracker.client_counts_by_ip.remove(&self.ip).unwrap();
```
Comment (Akuli) [inline src/ip_tracker.rs:28]: maybe:

```suggestion
            tracker.client_counts_by_ip.remove(&self.ip).unwrap();
```
